In [2]:
#import pandas library and name it pd
import pandas as pd

In [3]:
#create a dataframe by reading AAPL file
df=pd.read_excel('C:\\pyt\\AAPL.xlsx')

In [4]:
#list first five data
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2023-06-26,186.830002,188.050003,185.229996,185.270004,184.291275,48088700
1,2023-06-27,185.889999,188.389999,185.669998,188.059998,187.066544,50730800
2,2023-06-28,187.929993,189.899994,187.600006,189.250000,188.250244,51216800
3,2023-06-29,189.080002,190.070007,188.940002,189.589996,188.588455,46347300
4,2023-06-30,191.630005,194.479996,191.259995,193.970001,192.945328,85069600

In [5]:
#list last five rows
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
247,2024-06-18,217.589996,218.630005,213.000000,214.289993,214.289993,79943300
248,2024-06-20,213.929993,214.240005,208.850006,209.679993,209.679993,86172500
249,2024-06-21,210.389999,211.889999,207.110001,207.490005,207.490005,246421400
250,2024-06-24,207.720001,212.699997,206.589996,208.139999,208.139999,80727000
251,2024-06-25,209.149994,211.380005,208.610001,209.070007,209.070007,55549700

In [6]:
#list first two rows
df.head(2)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2023-06-26,186.830002,188.050003,185.229996,185.270004,184.291275,48088700
1,2023-06-27,185.889999,188.389999,185.669998,188.059998,187.066544,50730800

In [7]:
#print average volume
df['Volume'].mean()

60161911.11111111

In [8]:
#get maximum open price
df['Open'].max()

217.589996

In [11]:
#display column name
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [12]:
#print summmary info of the data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       252 non-null    datetime64[ns]
 1   Open       252 non-null    float64
 2   High       252 non-null    float64
 3   Low        252 non-null    float64
 4   Close      252 non-null    float64
 5   Adj Close  252 non-null    float64
 6   Volume     252 non-null    int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 13.9 KB

In [13]:
#calculate the HPR
df['HPR']=df['Close']/df['Open']

In [21]:
df.head(2)

,Date,Open,High,Low,Close,Adj Close,Volume,HPR,HPY,Range
0,2023-06-26,186.830002,188.050003,185.229996,185.270004,184.291275,48088700,0.991650,0.008350,2.820007
1,2023-06-27,185.889999,188.389999,185.669998,188.059998,187.066544,50730800,1.011674,-0.011674,2.720001

In [23]:
#calculate the HPY
df['HPY']=df['HPR']-1

In [24]:
df.head(3)

,Date,Open,High,Low,Close,Adj Close,Volume,HPR,HPY,Range
0,2023-06-26,186.830002,188.050003,185.229996,185.270004,184.291275,48088700,0.991650,-0.008350,2.820007
1,2023-06-27,185.889999,188.389999,185.669998,188.059998,187.066544,50730800,1.011674,0.011674,2.720001
2,2023-06-28,187.929993,189.899994,187.600006,189.250000,188.250244,51216800,1.007024,0.007024,2.299988

In [25]:
df['Range']=df['High']-df['Low']

df.head(1)

In [22]:
#import numpy as np
import numpy as np

In [26]:
np.mean(df['HPY'])

0.000491986555645473

In [27]:
df.to_excel('C:\\pyt\\output.xlsx', index=False)